### ISSUE TITLE
The exporter does not work correctly

### ISSUE THREAD

**Issue by HaydenHu** [30350n/pcb2blender#1]
![image](https://user-images.githubusercontent.com/30103277/175766387-15c8a706-fbec-4579-8923-6977701606b6.png)
KICAD6.0.6
Win10

**Comment by 30350n** [comment]
Should be fixed in the [v1.2 release](https://github.com/30350n/pcb2blender/releases/tag/v1.2-k6.0-b3.1). Can you try that one and confirm that it works now?

**Comment by HaydenHu** [comment]
> Should be fixed in the [v1.2 release](https://github.com/30350n/pcb2blender/releases/tag/v1.2-k6.0-b3.1). Can you try that one and confirm that it works now?

The exporter is ready to use, but the run icon does not load correctly. And after the importer is installed in blender3.1/3.2, it will freeze when I enable it, causing blender to crash

**Comment by 30350n** [comment]
Made another release ([v1.3](https://github.com/30350n/pcb2blender/releases/tag/v1.3-k6.0-b3.2)) to fix that.
Blender freezing when enabling the addon for the first time is normal, because its installing some dependencies.
It shouldn't throw an error/crash though.

**Comment by HaydenHu** [comment]
> 制作了另一个版本（[v1.3](https://github.com/30350n/pcb2blender/releases/tag/v1.3-k6.0-b3.2)）来解决这个问题。 首次启用插件时 Blender 冻结是正常的，因为它安装了一些依赖项。 它不应该抛出错误/崩溃。

![image](https://user-images.githubusercontent.com/30103277/175801086-a6104791-a8bb-4069-a6e1-c0aeac711f86.png)
![image](https://user-images.githubusercontent.com/30103277/175801123-15655d08-8932-4c28-9536-cc75d02392fa.png)

**Comment by 30350n** [comment]
urgh .... seems like cairosvg requires a bunch of dlls that don't get installed via pip.
For now you should be able to fix that by installing a GTK+ runtime https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer (mingw also comes with it I think). That's not a good/permanent solution though, will have to use something else to rasterize the gerbers/svgs I guess ...

**Comment by HaydenHu** [comment]
> urgh .... seems like cairosvg requires a bunch of dlls that don't get installed via pip. For now you should be able to fix that by installing a GTK+ runtime https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer (mingw also comes with it I think). That's not a good/permanent solution though, will have to use something else to rasterize the gerbers/svgs I guess ...

Yes, but the importer option only appears once when the plugin is enabled, disappears if it is closed and turned back on, and needs to be enabled again for the plugin to appear

**Comment by 30350n** [comment]
> Yes, but the importer option only appears once when the plugin is enabled, disappears if it is closed and turned back on, and needs to be enabled again for the plugin to appear
That sounds odd. If the plugin registers fine once, I don't really see why it wouldn't register again fine later aswell...
Are there any errors in the system console (`Window -> Toggle System Console` in Blender) when that happens?

**Comment by HaydenHu** [comment]
> > Yes, but the importer option only appears once when the plugin is enabled, disappears if it is closed and turned back on, and needs to be enabled again for the plugin to appear
> 
> That sounds odd. If the plugin registers fine once, I don't really see why it wouldn't register again fine later aswell... Are there any errors in the system console (`Window -> Toggle System Console` in Blender) when that happens?

![image](https://user-images.githubusercontent.com/30103277/175915355-adcc351c-fde0-4047-9e5d-d58a072d6de8.png)

**Comment by 30350n** [comment]
Thanks, fixed on master for now. Will make another release as soon as I figured out a better replacement for cairo.

**Comment by 30350n** [comment]
I completely got rid of cairo now, so all the GTK+ installation stuff shouldn't be required anymore. I also fixed the issue with the icon. Can you test the [1.4 release](https://github.com/30350n/pcb2blender/releases/tag/v1.4-k6.0-b3.2) and see if everything works now?

**Comment by HaydenHu** [comment]
> 我现在完全摆脱了 cairo，所以不再需要所有 GTK+ 安装的东西了。我还解决了图标的问题。你能测试一下[1.4 版本](https://github.com/30350n/pcb2blender/releases/tag/v1.4-k6.0-b3.2)，看看现在是否一切正常吗？

The pcb3d imported by blender has only PCB and no electronic component model
![image](https://user-images.githubusercontent.com/30103277/176117646-e74c619a-60b7-44c8-bd9e-4340f7ea1517.png)
![image](https://user-images.githubusercontent.com/30103277/176117947-ca9ab145-6b4e-4248-a265-fdfdfc23c372.png)

**Comment by 30350n** [comment]
Any errors in the system console after importing?
Also, are the components present in the KiCad 3D viewer?

**Comment by HaydenHu** [comment]
> 导入后系统控制台中是否有任何错误？ 此外，KiCad 3D 查看器中是否存在组件？

![image](https://user-images.githubusercontent.com/30103277/176122882-51cf1d57-6a8c-4a2a-9567-7dd0895db8ee.png)
![image](https://user-images.githubusercontent.com/30103277/176123456-94ec9751-c772-4835-94d1-23ded943b4aa.png)

**Comment by 30350n** [comment]
Try reexporting the file with the new v1.4 exporter.

**Comment by 30350n** [comment]
Any more errors?
If not, can you share the `.pcb3d` file?

**Comment by HaydenHu** [comment]
[123.zip](https://github.com/30350n/pcb2blender/files/8998916/123.zip)
I didn't find any other bugs, only the version number didn't change and it's still 1.1.0

**Comment by 30350n** [comment]
And this one is also fixed in [v1.5](https://github.com/30350n/pcb2blender/releases/tag/v1.5-k6.0-b3.2).
Thanks a lot for reporting all the issues and all your testing! ❤️
