### ISSUE TITLE
Importer installation issue in Blender 3.4

### ISSUE THREAD

**Issue by oliv33bx** [30350n/pcb2blender#12]
Thanks @30350n  for the new version of exporter-importer.
However, I tried to install the importer plugin in blender 3.4 but it does not appear in the plugin list.

_Originally posted by @oliv33bx in https://github.com/30350n/pcb2blender/issues/11#issuecomment-1435660667_

**Comment by 30350n** [comment]
What OS are you on?

**Comment by oliv33bx** [comment]
Windows 10

**Comment by 30350n** [comment]
How are you installing the plugin exactly? (just describe what you're doing, step by step)

**Comment by oliv33bx** [comment]
In Blender, I select edit/preferences/add-on/install
I choose the doswnloaded file pcb2blender_importer_2-2.zip and click install.
The plugin appears in the non active plugins list and when I try to activate it, an error occurs
I tried to remove the plugin in order to re-intall it but an error occurs and I can not remove the plugin (PermissionError...)

**Comment by oliv33bx** [comment]
Finally I managed to uninstall and reinstall the importer plugin and now it works !
Sorry for the inconvenience !
