### ISSUE TITLE
Issue enabling Blender importer

### ISSUE THREAD

**Issue by msasdk** [30350n/pcb2blender#13]
Ubuntu 22.04
Blender 3.41
Tried both snap as well as blender-3.4.1-linux-x64.tar.xz directly from blender.org

Both result in following error.
![image](https://user-images.githubusercontent.com/13538204/219951483-24d2d097-de83-432c-b110-514d0e830ac2.png)

Blender > Edit > Preferences > Add-ons > Install, browse to .zip and enable.

**Comment by 30350n** [comment]
You'll need to have pip installed on whatever python installation is being used by Blender. Installing via the [get-pip.py](https://pip.pypa.io/en/stable/installation/#get-pip-py) is the most reliable way.

**Comment by msasdk** [comment]
Thanks!
