### ISSUE TITLE
python bundled with Blender 3.4.1 does not have the pip module

### ISSUE THREAD

**Issue by Snevzor** [30350n/pcb2blender#14]
~/blender-3.4.1-linux-x64/3.4/python/bin$ ./python3.10 -m pip
/home/sven/blender-3.4.1-linux-x64/3.4/python/bin/python3.10: No module named pip

Traceback (most recent call last):
  File "/home/sven/blender-3.4.1-linux-x64/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/sven/.config/blender/3.4/scripts/addons/pcb2blender_importer/__init__.py", line 36, in <module>
    subprocess.check_call((
  File "/home/sven/blender-3.4.1-linux-x64/3.4/python/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/home/sven/blender-3.4.1-linux-x64/3.4/python/bin/python3.10', '-m', 'pip', 'install', '--no-deps', 'skia-python', '-t', '/home/sven/.config/blender/3.4/scripts/addons/pcb2blender_importer/site-packages')' returned non-zero exit status 1.

https://github.com/30350n/pcb2blender/blob/dbd48c6e69a60a9286ad10f26e0e0650ad18661a/pcb2blender_importer/__init__.py#L34

Tested with v2.3

**Comment by 30350n** [comment]
Checkout #13

**Comment by Snevzor** [comment]
Thanks! My apologies for not checking earlier issues.

**Comment by 30350n** [comment]
No worries. I'm currently looking into automating dependency/pip installation further. This should make this process more straight forward in the future.
