### ISSUE TITLE
PCB colours/Shaders doesn't use stack-up colours?

### ISSUE THREAD

**Issue by UnexpectedMaker** [30350n/pcb2blender#18]
This project is fantastic!  I just found it and it works really well :)

Only issue I'm having at the moment is that the PCB colours are always green - not matter what my stickup colours are set to.

Is that the correct behaviour? 

I know I can alter them in the blender shader tree, but that seems to be running really slow on imported PCBs using Blender 3.4.1 on MacOS (Intel), so I was hoping I could skip trying to tweak them in that.

Cheers and keep up the great work!

Seon
Unexpected Maker

**Comment by 30350n** [comment]
Hey, thanks a lot for the kind words!

The current materials are unfortunately not really optimized for lower end hardware / rendering without a dedicated GPU, this is something I'm planning to improve in the future.
You should be able to tweak the colors in "Solid Mode" though, without rendering, but you won't see the changes immediately of course.

Regarding the stackup, that's unfortunately not easily accessible in KiCad via the python api. There's some discussion about this topic [here](https://github.com/30350n/pcb2blender/issues/8#issuecomment-1346681765). @haschtl has a fork of this addon where they tried implemented this iirc, but it might be outdated.

**Comment by UnexpectedMaker** [comment]
Thanks for the quick reply, much appreciated!

My testing last night was on a 2018 MBP with dedicated GPU, but yes, mobile. I'm at work now so I'll install everything on my i9 iMac today and see if I get any better performance with the shader.

BTW, I'm using blender 3.4.1 because I could't work out how to get bast that material error when installing into 3.5.1 - any idea on that?

Thanks again!

**Comment by UnexpectedMaker** [comment]
Ignore my materials comment - it's all working now.    But I am seeing some weird floating 3d object issues, so will open a new issue on that. 

BTW, your shaders look amazing ! Now I understand why they take so long to process and why they are so big!

**Comment by 30350n** [comment]
> Thanks for the quick reply, much appreciated!
> 
> My testing last night was on a 2018 MBP with dedicated GPU, but yes, mobile. I'm at work now so I'll install everything on my i9 iMac today and see if I get any better performance with the shader.
> 
> BTW, I'm using blender 3.4.1 because I could't work out how to get bast that material error when installing into 3.5.1 - any idea on that?
> 
> Thanks again!

I was holding back on a new release for some time, because I wanted to add a test for the 3.5.0 crash first. Just found some time to do that though, so the [v2.6](https://github.com/30350n/pcb2blender/releases/tag/v2.6-k7.0-b3.5) release should work on 3.5.1 now.

**Comment by UnexpectedMaker** [comment]
Working great, thanks!
