### ISSUE TITLE
Floating solder blobs...

### ISSUE THREAD

**Issue by UnexpectedMaker** [30350n/pcb2blender#19]
I am seeing many of the little solder blobs you generate floating above the pads, either half way up a component, or above them, like with the 0201 resistors you can see in this image....
<img width="883" alt="floating_blobs" src="https://github.com/30350n/pcb2blender/assets/3156212/6fa9a179-6a54-47e9-9540-0b25bfc6b905">

The 0201 resistors are just the standard models in KiCAD, as are the 0402 ones that don't have this issue.

I'm unsure how they are detected to be generated, or why they might be floating.

Any idea what I need to do in my model or data to solve this?

Thanks :)

P.S. this is in 2.6, but I also saw it n 2.5 and 2.4.

**Comment by 30350n** [comment]
Hmm this is odd, could it be that this is a <1.6mm board? I think I might have 1.6mm hard coded as the pcb thickness somewhere 😅 . That wouldn't explain why it seemingly only happens for some components though? Odd.
Would you mind sharing the .pcb3d file so I could take a look?

**Comment by UnexpectedMaker** [comment]
Yeah, it's a 1mm thickness board. Is there a way I can share the board with you, but not publicly?

**Comment by 30350n** [comment]
Sure, you can send it to mail@30350n.de if you want .... but actually I had some time on hand so I implemented basic stackup support ^^.

Here's a prerelease for the exporter and importer (you need to reexport the .pcb3d files) which should fix the pcb thickness issues, as well as automatically use your defined stackup colors:
[pcb2blender_exporter_3-0.zip](https://github.com/30350n/pcb2blender/files/11518011/pcb2blender_exporter_3-0.zip)
[pcb2blender_importer_3-0.zip](https://github.com/30350n/pcb2blender/files/11518012/pcb2blender_importer_3-0.zip)

**Comment by UnexpectedMaker** [comment]
Wicked, trying this now!

**Comment by UnexpectedMaker** [comment]
Ok, that seems to fix it and it brought in the correct board thickness and colour!
Thanks heaps :)
<img width="1284" alt="Screenshot 2023-05-20 at 9 27 23 am" src="https://github.com/30350n/pcb2blender/assets/3156212/8a628874-3838-4112-b3a9-d88489bd5eef">
