### ISSUE TITLE
Inconsistency with solder blob generation for pads....

### ISSUE THREAD

**Issue by UnexpectedMaker** [30350n/pcb2blender#22]
Some components have the "generated solder blobs" for the pads and some components don't - possibly only the KiCAD built in model do?

I've highlighted some good areas in green and bad in red as an example.
![solder_blobs_example](https://github.com/30350n/pcb2blender/assets/3156212/76fdda76-27c7-435b-89ce-61c3334ced1e)

 How do I get them to be added to all components? Is there something teh script is looking for in the component name? or in a property setting somewhere?

Thanks :)

**Comment by 30350n** [comment]
The conditions for "SMART" solder joint generations are as follows:
1. The component has to have a 3d model and be either THT or SMD
2. The pad has to
    - have the according Paste layer selected as a technical layer
    - be one of these pad shapes: CIRCLE, OVAL, RECT, ROUNDRECT
  
You can check if the Paste layer is enabled in KiCad here:
![image](https://github.com/30350n/pcb2blender/assets/34186858/f3464aa8-ae5c-459e-9377-b332a3e6c982)

If it's an unsupported pad shape, there should be a warning in the system console in Blender.

**Comment by UnexpectedMaker** [comment]
Ok, perfect, thanks!
Seems I had a bunch of footprints set as "Unspecified" - whoops!
Love your work :)
