### ISSUE TITLE
Using solder mask color from setup

### ISSUE THREAD

**Issue by N0cynym** [30350n/pcb2blender#26]
Dear @30350n 

I love this project and I'm happy to use your work in [KiBot](https://github.com/INTI-CMNB/KiBot) so I can create beautiful deployments automatically.

One question:

I there a way of using the solder mask color which is defined in the stackup setup:

```
(setup
    (stackup
      (layer "F.SilkS" (type "Top Silk Screen") (color "White"))
      (layer "F.Paste" (type "Top Solder Paste"))
      (layer "F.Mask" (type "Top Solder Mask") (color "Black") (thickness 0.01))
      (layer "F.Cu" (type "copper") (thickness 0.035))
      (layer "dielectric 1" (type "core") (thickness 1.51) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))
      (layer "B.Cu" (type "copper") (thickness 0.035))
      (layer "B.Mask" (type "Bottom Solder Mask") (color "Black") (thickness 0.01))
      (layer "B.Paste" (type "Bottom Solder Paste"))
      (layer "B.SilkS" (type "Bottom Silk Screen") (color "White"))
      (copper_finish "None")
      (dielectric_constraints no)
    )
```

![grafik](https://github.com/30350n/pcb2blender/assets/75754060/1ccb7d91-89fa-4a3c-87b1-ee822c0e85da)

Best regards :v:

**Comment by 30350n** [comment]
This is already implemented, there's just no release containing it yet. [Here's](https://github.com/30350n/pcb2blender/issues/19#issuecomment-1554710050) a prerelease addon containing the feature if you want to check it out.
