### ISSUE TITLE
Blender 3.6 support

### ISSUE THREAD

**Issue by LorenzoGuerro** [30350n/pcb2blender#27]
Hi,

I just updated to Blender 3.6 and it seems like the materials/shaders are not working anymore. In viewport-shading "rendered" the PCB board is black and not showing anything (worked in Blender 3.5.1). Viewport shading "Material preview" still works though.

**Comment by 30350n** [comment]
Seems to be working fine for me, is this problem only present with old blend files or with freshly imported objects too? Also, are you sure you have the addon enabled in 3.6?

**Comment by LorenzoGuerro** [comment]
I found out that I haven't enabled the add-on in Blender 3.6. Thanks for helping - everything is working again!
