### ISSUE TITLE
when import to blender, no trace/ lost pad?/ no silk ?

### ISSUE THREAD

**Issue by chopin1998** [30350n/pcb2blender#34]
![2023-10-08_17-42](https://github.com/30350n/pcb2blender/assets/643792/7439b5ae-3e2c-4310-8e62-17b5b30e1836)

**Comment by sergiynesterenko90** [comment]
@chopin1998 @30350n I'm seeing the same thing, what was the resolution?

**Comment by 30350n** [comment]
Going into material/rendered mode.

**Comment by sergiynesterenko90** [comment]
Yup, spot on. Blender newb. This is what it looks like in the Blender editor until you actually render. Thank you!!
