### ISSUE TITLE
Export error with the latest 2.7 release

### ISSUE THREAD

**Issue by ojthetiny** [30350n/pcb2blender#35]
Updated my plugin to the new 2.7 version and now I can't export the file out of kicad, error message seems to be permission related despite running kicad as admin
![Screenshot 2023-10-08 140658](https://github.com/30350n/pcb2blender/assets/65928618/793fe023-a707-45a5-b309-9f369435f9f7)

**Comment by 30350n** [comment]
Hm, that is weird. For some reason you don't seem to have permission to delete the `pcb2blender_tmp` folder. Try deleting it manually from your file explorer (only the `pcb2blender_tmp` part, **not** the whole `Local\Temp` folder). That should fix it.
You should never be required to have admin permissions to use the addon btw.

**Comment by ojthetiny** [comment]
yes, that did the trick, thank you
