### ISSUE TITLE
How to render PTH? 

### ISSUE THREAD

**Issue by VIPQualityPost** [30350n/pcb2blender#37]
My PTH always are showing as filled with solder, which is OK in some cases (like unpopulated THT parts) but for others (like mounting holes) this is not desired. Is there a way to indicate which holes should be filled? or is this an issue with the footprints? I am using the default KiCad "pad" PTH mounting hole footprint.
Example, the corner holes here: 
![render](https://github.com/30350n/pcb2blender/assets/46805787/f69b82ae-e6ef-44c5-a8c6-27690313def6)

**Comment by VIPQualityPost** [comment]
oh, they just get filled with a solder blob object. you can highlight it in blender and just delete it!

**Comment by 30350n** [comment]
Hmmm this seems weird, normally mounting holes, unpopulated components etc. shouldn't get those solder blobs. Do you have the "Add Solder Joints" setting set to "Smart"?
![image](https://github.com/30350n/pcb2blender/assets/34186858/53585489-ebce-4a81-a8f2-4a7aee36432f)

**Comment by VIPQualityPost** [comment]
I didn't try tinkering with those settings yet - let me see.

**Comment by 30350n** [comment]
Hmmm, well it should be set to "Smart" by default. If it still includes the solder blobs with that setting, could you double check what footprints you are using (mainly for the mounting holes I guess) and possibly also share the .pcb3d file?

**Comment by VIPQualityPost** [comment]
Should the mounting holes be marked "do not populate"? I suppose so, right? I haven't set that. 
It is set to "smart".

**Comment by 30350n** [comment]
They shouldn't be drawn if they are DNP, yeah (though that'd make more sense for components which *could* actually be assembled). For mounting holes, the Pad should be set to NPTH, Mechanical.
![image](https://github.com/30350n/pcb2blender/assets/34186858/1e072dde-556e-490b-822c-4481ac1394bf)

(There's a few more conditions like, there won't be any solder if no 3D model is defined for example).
