### ISSUE TITLE
Blender 3.4 crashes with code EXCEPTION_ACCESS_VIOLATION while viewing PCB on material preview

### ISSUE THREAD

**Issue by SerialDesignatorN** [30350n/pcb2blender#39]
I am forced to use Blender 3.4 due to my compabilities, and I use pcb2blender v2.4 (export & import), but when I entered material preview on the PCB, it crashed. Crash text:
```
# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FFFA1A42110
Exception Module      : ig7icd64.dll
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x00000000000000A8
```
Please help me ASAP!

**Comment by 30350n** [comment]
Could be pretty much anything, in this case this sounds like more of a Blender issue than something directly caused by the addon. Could be insufficient resources too I guess.
