### ISSUE TITLE
No pads or silk

### ISSUE THREAD

**Issue by bretskee** [30350n/pcb2blender#41]
using blender 4.0 and kicad 7.0.1. Pads and silk screens do not appear. Dont know if this is export or import issue (or just finger trouble)

**Comment by 30350n** [comment]
Whst OS are you on?

**Comment by bretskee** [comment]
Windows 11 Version 22H2 (OS Buikd 22621.2861)

**Comment by 30350n** [comment]
Ok, try to open the System Console in Blender (`Window -> Toggle System Console`) before importing. See if any errors come up in there. You can also share the `.pcb3d` file if you want.

**Comment by bretskee** [comment]
The console is silent. My .pcb3d file is attached renamed as .txt.

[EXPORT.txt](https://github.com/30350n/pcb2blender/files/13847128/EXPORT.txt)

**Comment by 30350n** [comment]
Looks good to me. You just have to go into rendered mode, guess you didn't do that?
![image](https://github.com/30350n/pcb2blender/assets/34186858/dc574728-b808-4efe-b7d7-946889164d8c)

**Comment by bretskee** [comment]
Guess not... thanks.
