### ISSUE TITLE
Exception on python Action plugin code

### ISSUE THREAD

**Issue by CWE-119** [30350n/pcb2blender#44]
it worked for once when i checked it on test file 
after that it never worked 
idk why
i reinstalled everything , all the plugins , it didnt worked , not even with the test file i used in the first test 
![image](https://github.com/30350n/pcb2blender/assets/86527233/698737e4-5dc0-4dcd-8cfc-65699be4f474)

**Comment by CWE-119** [comment]
![image](https://github.com/30350n/pcb2blender/assets/86527233/644ae6d8-6086-4ec8-824a-7925be47dde2)
![image](https://github.com/30350n/pcb2blender/assets/86527233/c03af38f-acee-4461-b79c-355a46199cfc)

**Comment by CWE-119** [comment]
kicad v 7.0

**Comment by 30350n** [comment]
Try manually deleting the tempdir, that should fix it for now.
![image](https://github.com/30350n/pcb2blender/assets/34186858/3a0c35cc-b9f2-4f98-9994-898a1f5de0d4)

**Comment by CWE-119** [comment]
dyamm thanks <3
