### ISSUE TITLE
kicad8.0 rc support

### ISSUE THREAD

**Issue by HaydenHu** [30350n/pcb2blender#46]
**pcb2blender2.8**
```
Application: KiCad PCB Editor x64 on x64

Version: 8.0.0-rc1-79-gf80094e7c5, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 10 (构建 19045)，64位版, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jan 19 2024 09:03:46
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

```
The exported model has no components and no materials

**Comment by 30350n** [comment]
As long as you get a .pcb3d file, that shouldn't be an exporter issue though I'm pretty sure. Can you share the `.pcb3d` file?

**Comment by HaydenHu** [comment]
> As long as you get a .pcb3d file, that shouldn't be an exporter issue though I'm pretty sure. Can you share the `.pcb3d` file?

[123.zip](https://github.com/30350n/pcb2blender/files/13999002/123.zip)

**Comment by 30350n** [comment]
Looks good to me.
![image](https://github.com/30350n/pcb2blender/assets/34186858/a4466b67-484f-43f8-b2b3-a01e099519c1)

The board seems to be cut off, but that is probably due to incorrect board defs. You generally don't need to provide those for single (non panelized) PCBs.

**Comment by HaydenHu** [comment]
![S8ZF%AHVFAHB9FK1@YA`YFV](https://github.com/30350n/pcb2blender/assets/30103277/2c5706d1-bff4-42f7-b66c-cd0a86fa929f)
OK
