### ISSUE TITLE
Error installing addon on blender

### ISSUE THREAD

**Issue by aeonSolutions** [30350n/pcb2blender#47]
Hi there @30350n 

I tried installing the addon on blender 4.0 (windows 11) , and spite the log showing  a successful installation in

Modules Installed () from 'C:\\Users\\Aeon\\Desktop\\pcb2blender_importer.zip' into 'C:\\Users\\Aeon\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'"

the addon does not show anywhere for me to enable in the preferences dialog box .

What am i doing wrong ? 
thank you

**Comment by 30350n** [comment]
You probably didn't install the required dependencies in the Preferences window. Under Preferences -> Addons (search for pcb2blender).

**Comment by aeonSolutions** [comment]
I did that however It shows nothing.

**Comment by aeonSolutions** [comment]
Here's a snapshot of my screen 
![image_2024-02-27_181045068](https://github.com/30350n/pcb2blender/assets/7936768/8a2f1ba3-84d0-4880-8052-e4545808404c)

**Comment by 30350n** [comment]
Where did you download the zip from? You have to download from the latest release.

**Comment by aeonSolutions** [comment]
you are correct. I downloaded from the latest release.

**Comment by 30350n** [comment]
Did you rename the zip file then? Or unpack it and pack it again? The correct file from the latest release is named `pcb2blender_importer_2-9.zip`. You have to install that file in Blender.

**Comment by aeonSolutions** [comment]
Solved. It turs out i was trying to install the exporter file . 
thank you

**Comment by 30350n** [comment]
Oh yeah, that also doesn't work obviously 😅
