### ISSUE TITLE
Import error - Mesh has no attribute as auto smooth

### ISSUE THREAD

**Issue by ns2gupta** [30350n/pcb2blender#53]
Hi, 

I recently installed plugin on kicad 7 and on blender 4.1. I was able to generate the pcb3d file using text tags (PCB3D_TL_<>). 
However when i try to import it on blender, it gives me this error 

![image](https://github.com/30350n/pcb2blender/assets/39019003/522aae95-399b-4fd0-bef6-c5ce3bdfe58a)

**Comment by 30350n** [comment]
Blender 4.1 is not supported (yet). It came out like yesterday.

**Comment by ns2gupta** [comment]
oh i see, let me try with previous version. Thanks for the quick response

**Comment by ns2gupta** [comment]
4.0 worked!
