### ISSUE TITLE
Cant export or inport 

### ISSUE THREAD

**Issue by BretterBote** [30350n/pcb2blender#61]
I am getting an Error in KiCAD and Blender. In Blender when i activate the plugin, nothing shows up under File > Import. I started Blender as an Admin and got an Error. Same happened when i tried to export the pcb3d from KiCAD. Couldn´t copy the text so i took a screenshot. 

![Error](https://github.com/30350n/pcb2blender/assets/118048956/21852632-cf5b-4e2b-9a8a-54928456cf74)
![Error2](https://github.com/30350n/pcb2blender/assets/118048956/1def47c4-fcb8-45b8-a566-b5315e08ead6)

**Comment by 30350n** [comment]
The second error is due to insufficient permissions to open the path you've selected for writing. Either you're trying to export to some system directory or you've got messed up permissions on your system.

**Comment by 30350n** [comment]
First one could either be a collision with another addon or something messed up while installing the dependencies, which makes it so that PIL is detected as being installed, but the installation is corrupted.
Either way you shouldn't (have to) start Blender with elevated permissions.

**Comment by 30350n** [comment]
Closing this, as it should be resolved by installing the newest [v2.13](https://github.com/30350n/pcb2blender/releases/tag/v2.13-k8.0-b4.2) version which uses the new [Blender Extension Format](https://extensions.blender.org/about/)!
