### ISSUE TITLE
Feature Request: ENIG finish on pads with no paste

### ISSUE THREAD

**Issue by Henrik-Wo** [30350n/pcb2blender#63]
Hi,
I think the plugin is great and I really enjoy working with it! However, I would have one suggestion for improvement: Would it be possible for pads, castellations, etc. that don't have a "paste" to be displayed in an ENIG finish?

**Comment by 30350n** [comment]
That should already work. You can either manually select the ENIG finish in the shader graph or select it in your KiCad stackup settings (then it'll be selected in the shader automatically).

**Comment by Henrik-Wo** [comment]
Found it, thank you very much!
