### ISSUE TITLE
Dark stripes/shadows on PCB

### ISSUE THREAD

**Issue by Fivefold** [30350n/pcb2blender#64]
I get some weird dark stripes on the exported/imported pcbs (see pictures below). They don't seem to be lighting-related, as they persist for different lighting conditions and even when removing all components but the PCB itself.

It could be a blender issue since I'm a total beginner in blender, but even if I start a new project and import the pcb I can see the stripes. They also always stay in the same locations.

Not sure how to even tackle this. I can send you the blender files privately if it helps to track down the issue.

Used versions:
Kicad 8.0.2
Blender 4.1.1
pcb2blender kicad plugin 2.10 (from kicad plugin manager)
pcb2blender importer 2.11.0

<details><summary>Show images</summary>

![image](https://github.com/30350n/pcb2blender/assets/38764218/d5e8eb6c-a586-4863-8e46-42a6c05d1e9c)

![image](https://github.com/30350n/pcb2blender/assets/38764218/07c088f9-ce1a-4809-95a1-4694e82c4e63)

![image](https://github.com/30350n/pcb2blender/assets/38764218/7a7a6f8a-1294-4109-99f8-b25007a33e84)

</details>

**Comment by 30350n** [comment]
Probably an issue with the Boolean modifier again ...

If you are only using a single PCB, you don't have to specify it's bounds in KiCad, which should fix this.

For investigating the issue though: It'd be nice if you could share the `.pcb3d` file (if you want to do so privately, you can find my discord, e-mail and mastodon on [my personal website](https://30350n.de/)).

**Comment by Fivefold** [comment]
I _am_ using single PCBs and I haven't specified it's bounds (in case you mean with the PCB3D_<TL/BR>_<boardname> text). Due to your suggestion I tried specifying the bounds and I don't see any stripes there! So there's a workaround.

I've sent you a request on discord to send you the .pcb3d file.

**Comment by 30350n** [comment]
This is fixed in [v2.12](https://github.com/30350n/pcb2blender/releases/tag/v2.12-k8.0-b4.1)!
