### ISSUE TITLE
Exception after re-exporting: FileExistsError: [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by wilhelmzeuschner** [30350n/pcb2blender#67]
I exported a PCB once, into the wrong folder. 
On the second try, I also realized that at first I forgot to add the TL and BR text items and I picked the correct folder.

Now I get this error:
`FileExistsError: [WinError 183] Cannot create a file when that file already exists`
![image](https://github.com/user-attachments/assets/4f72a6cd-17bc-422c-8ec1-ff329b9f9c38)

I went into the temporary folder to find this:
![image](https://github.com/user-attachments/assets/4d54450a-f97f-4f98-949b-9966efbe7738)

I deleted all the temp files and did another export.
Now it worked fine.

Then I tried to export again and got the same error again.
So I guess the error is not related to the missing TL and BR text, nor the fact I re-exported to different paths.

**Comment by 30350n** [comment]
Thanks for the report! Should be fixed with [01e49f5](https://github.com/30350n/pcb2blender/commit/01e49f57e91b777ce81336a5594433bbc2871e09).

You do not need the "TL and BR text items" if you are only exporting a single PCB btw.
