### ISSUE TITLE
Plugin not working with Blender 4.2

### ISSUE THREAD

**Issue by inF1704** [30350n/pcb2blender#70]
Tried to install the plugin on Blender 4.2 but without success. 

Workaround: downgrade Blender to 4.11 and installing the plugin

**Comment by 30350n** [comment]
Duplicate of #69. Blender 4.2 is not supported yet.

**Comment by 30350n** [comment]
Blender 4.2 is supported now in [v2.13](https://github.com/30350n/pcb2blender/releases/tag/v2.13-k8.0-b4.2)!
