### ISSUE TITLE
Unable to import .pcb3d file to blender

### ISSUE THREAD

**Issue by Georgeeden** [30350n/pcb2blender#71]
I am unable to import the file to blender after installing the add-in.

![Install skia-python pillow](https://github.com/user-attachments/assets/6228ebc3-3a4e-4643-b91a-8a6150e98df9)
![After install](https://github.com/user-attachments/assets/f698324c-5126-4c25-9b3e-e9288078f6ea)
![Trying to import](https://github.com/user-attachments/assets/cfd4d181-996e-4fd4-be35-629509b191e5)

Any ideas on how to resolve this would be appriciated (Hopefully it is me just doing something wrong, I am still new to blender).

**Comment by 30350n** [comment]
Blender 4.2 is not supported yet.

**Comment by Georgeeden** [comment]
Thanks, for anyone wanting to install the correct Blender version, it can be found here: https://download.blender.org/release/Blender4.1/blender-4.1.1-windows-x64.msi

**Comment by 30350n** [comment]
Blender 4.2 is supported now in [v2.13](https://github.com/30350n/pcb2blender/releases/tag/v2.13-k8.0-b4.2)!
