### ISSUE TITLE
Unable to install addon

### ISSUE THREAD

**Issue by homusman** [30350n/pcb2blender#72]
Attempted to install the adon via the usual Blender->Preferences->Addons->Install Zip

Blender says:
"Modules Installed () from 'C:\\Users\\janej\\Downloads\\pcb2blender_exporter_2-12.zip' into 'C:\\Users\\janej\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons' "
But the pcb2blender doesnt actually appear.

Tested in Blender 3.6 4.0 and 4.2.
Blender was restarted multiple times, machine was restarted too.

**Comment by 30350n** [comment]
pcb2blender currently only supports Blender 4.1.1.

**Comment by 30350n** [comment]
Blender 4.2 is supported now in [v2.13](https://github.com/30350n/pcb2blender/releases/tag/v2.13-k8.0-b4.2)!

**Comment by homusman** [comment]
Thank you! works like a charm. Would suggest leaving a note in the release notes as i did not find the compatibility info anywhere else.
