### ISSUE TITLE
I can't find PCB (.pcb3d) in the Import menu of Blender

### ISSUE THREAD

**Issue by Baott569vn** [30350n/pcb2blender#73]
I have added the package into Blender.

I imported the file into Blender via File -> Import -> PCB (.pcb3d), but nothing similar is showing up

![image](https://github.com/user-attachments/assets/c72d9273-b5b6-4a54-85d0-641b60bae54d)
![image](https://github.com/user-attachments/assets/789cb099-d36d-4ae5-9b57-2081ef6202bd)

I am using blender 3.4

**Comment by hemalchevli** [comment]
I think blender 3.4 is not suported, try Blender 4.1 works out of the box. Also don't forget to install the dependencies, it will show up when you expand the pcb2blender in the addon menu.
