### ISSUE TITLE
Error importing .PCB3D file into Blender.

### ISSUE THREAD

**Issue by FraserElectronics** [30350n/pcb2blender#74]
I am using the latest version of KiCad with the Export to Blender plugin. I export a simple PCB to disk and then try and import it into Blender 4.2.1.0 but the following error message is displayed:

![image](https://github.com/user-attachments/assets/777af833-4642-4c19-884f-6f93c9140d98)

Am I missing a step or what might be wrong?

Andy

**Comment by 30350n** [comment]
Ah, seems like that happens if you aren't in `Object Mode` when importing. Switching to `Object Mode` before should fix it.

**Comment by FraserElectronics** [comment]
Thanks for that 👍
I can now import my PCB however, I notice there are no tracks or Silkscreen - is that to be expected?

Andy

**Comment by 30350n** [comment]
Try to switch to `Rendered` view mode.

**Comment by FraserElectronics** [comment]
Okay, that is really cool.
Very nice plugin 👍

Andy

**Comment by 30350n** [comment]
Thanks!

The error when importing in edit mode will be fixed in the next version ^^
