### ISSUE TITLE
Error re-registering add-on (with fix)

### ISSUE THREAD

**Issue by ideasman42** [30350n/pcb2blender#77]
If you un-register and re-register this add-on, there is an error:
`pcb2blender_importer/__init__.py`

`ValueError: register_class(...): already registered as a subclass 'PCB2BLENDER_OT_import_pcb3d'`

This is caused by the register function always adding to `_modules`.

To fix this, at the start of  `register(..)` in `pcb2blender_importer/__init__.py` run: `_modules.clear()` .

**Comment by 30350n** [comment]
Fixed! Thanks for catching that and providing the fix ^^
