### ISSUE TITLE
Support Blender 4.3

### ISSUE THREAD

**Issue by goran-mahovlic** [30350n/pcb2blender#82]
Thank you for your project it is really amazing!

Last week I was successful in importing PCB that was exported from Linux KiCad, today I have updated plugin in blender as new one was available, and I am no more able to do the import

Error I am getting - even with older PCB that I was able to import last week

![Screenshot from 2024-11-22 13-28-27](https://github.com/user-attachments/assets/ab65608b-93e9-4d2c-ab71-1cb0a6344420)

Version of KiCad plugin ( it is same version as last time )

![Screenshot from 2024-11-22 13-23-11](https://github.com/user-attachments/assets/81ff8d8e-28e0-4716-b22a-838abb8ea9b0)

KiCad version

![Screenshot from 2024-11-22 13-21-23](https://github.com/user-attachments/assets/af380b0b-d080-4ba6-b878-add72fcce3a4)

Updated Blender plugin version that is not longer working on my side 

![Screenshot from 2024-11-22 13-20-12](https://github.com/user-attachments/assets/87d4c479-e3c4-43d8-aba6-ba95e779212b)

Best,
Goran

**Comment by 30350n** [comment]
Thanks!

You are using Blender 4.3 which came out 3 days ago and isn't supported yet.

**Comment by 30350n** [comment]
If it just closes that's probably a crash and iirc crash logs aren't exactly useful. I think this can sometimes be caused by custom models sometimes, you could try importing without 3D component models (there's an option for that in the import UI).

(You can also share the `.pcb3d` file if you want, then I could take a quick look at it.)

**Comment by goran-mahovlic** [comment]
I think I have low memory for this board, as I have lots of components.
I mainly work on open source boards, but unfortunately the one that fails is not open, so I am not able to share it.

When I get one of the open to fail I will let you know!

But here is the one that is open and I was able to import and render!

![ulx5m_pcbtoblender](https://github.com/user-attachments/assets/4c8dfefc-3f72-4b91-8b82-3085883e53f0)

Again, thank you on your support and making export/import easy!

**Comment by ziomau10** [comment]
Hi I also am facing this issue.
I can attach the pcb3d file of a board that gives similat traceback on a missing shadow_method as above.
Actually after the error I have in the viewport the PCB and the front traces and the front PADS.
No traces and no pads of the bottom side and no components.
Hope this helps you to find the problem.
[Sense.zip](https://github.com/user-attachments/files/18012704/Sense.zip)

Anyway great job!

**Comment by 30350n** [comment]
Blender 4.3 is supported now with [v2.16](https://github.com/30350n/pcb2blender/releases/tag/v2.16-k8.0-b4.2lts).
