### ISSUE TITLE
Cannot load PCB

### ISSUE THREAD

**Issue by blackbit42** [30350n/pcb2blender#85]
After experiencing various issues (https://github.com/30350n/pcb2blender/issues/62, https://github.com/30350n/pcb2blender/issues/65), I've downloaded a blender binary build, with which `pcb2blender` works fine for some simple kicad projects of mine.
Though, when I try to load [MAUreene_8226](https://github.com/blackbit42/MAUreene_8226), blender stalls with no CPU utilization. After hitting ctrl-C, I get this:
```
^CTraceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 84, in update_props
    self.inputs["Color"].default_value = (*srgb2lin(material.diffuse), 1.0)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/core.py", line 105, in srgb2lin
    def srgb2lin(color):
    
KeyboardInterrupt
File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 75, in update_props
^CTraceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 84, in update_props
    self.inputs["Color"].default_value = (*srgb2lin(material.diffuse), 1.0)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/core.py", line 105, in srgb2lin
    def srgb2lin(color):
    
KeyboardInterrupt
File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 75, in update_props
^CTraceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 157, in init
    self.init_node_tree(inputs, nodes, outputs)
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/custom_node_utils/__init__.py", line 52, in init_node_tree
    setup_node_tree(node_tree, nodes_def)
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/custom_node_utils/__init__.py", line 29, in setup_node_tree
    links.new(nodes[from_node].outputs[output_index], node.inputs[input_index])
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 81, in update_props
    material = self.get_material()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 165, in get_material
    color = "custom_" + rgb2hex(lin2srgb(self.inputs["Color"].default_value[:3]))
                                         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Color" not found'
File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 75, in update_props
Traceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 81, in update_props
    material = self.get_material()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 165, in get_material
    color = "custom_" + rgb2hex(lin2srgb(self.inputs["Color"].default_value[:3]))
                                         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Color" not found'
File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 75, in update_props
Traceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 81, in update_props
    material = self.get_material()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 165, in get_material
    color = "custom_" + rgb2hex(lin2srgb(self.inputs["Color"].default_value[:3]))
                                         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Color" not found'
File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 75, in update_props
Traceback (most recent call last):
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/importer.py", line 298, in execute
    enhance_materials(self.new_materials)
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/materials.py", line 75, in enhance_materials
    mat4cad_mat.setup_node_tree(node_tree)
  File "/home/blackbit/.config/blender/4.3/extensions/blender_org/pcb3d_importer/mat4cad/blender/__init__.py", line 37, in setup_node_tree
    node_shader.inputs["Color"].default_value = (*srgb2lin(self.diffuse), 1.0)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Color" not found'
^CTraceback (most recent call last):
  File "/home/blackbit/Downloads/blender-4.3.0-linux-x64/4.3/scripts/startup/bl_ui/properties_paint_common.py", line 17, in poll
    @classmethod

KeyboardInterrupt
```

I guess a property of the project is incompatible with `pcb2blender`?

**Comment by 30350n** [comment]
Can you share the `.pcb3d` file?

Looking at the logs you shared, this might all be caused by the `KeyboardInterrupt` you triggered via `Ctrl + C`. There's a good chance that it just takes a while to import.

**Comment by blackbit42** [comment]
[maureene.pcb3d.zip](https://github.com/user-attachments/files/18095593/maureene.pcb3d.zip)
That's the file I tried to load.

**Comment by 30350n** [comment]
Okay, testing it on my machine now.

Without even loading it though, there seem to be some relatively large models in there, which might take a while to load because the VRML from Blender I use is really poorly optimized.

![grafik](https://github.com/user-attachments/assets/aad1845b-2f6d-40be-b205-452b593a358f)

So it might be a good idea to reduce detail on those, if possible. (I've created [free2ki](https://github.com/30350n/free2ki/) to export pcb2blender friendly models from FreeCAD to KiCad).

**Comment by 30350n** [comment]
Here's an example for the 4PDT_Relay, exported via `free2ki`:

[4PDT_Relay.zip](https://github.com/user-attachments/files/18095899/4PDT_Relay.zip)

**Comment by blackbit42** [comment]
Oh, I wasn't aware you're into FreeCAD too.
This is super off-topic, I'll ask anyways (perhaps we should move this conversation somewhere else if it picks up pace...).
What I would like to achieve is to get various renders of a KiCAD PCB from KiCAD itself, FreeCAD and Blender, all with the same 'view'.
In FreeCAD there are some presets like [Std_ViewIsometric](https://wiki.freecad.org/Std_ViewIsometric) and [Std_ViewTrimetric](https://wiki.freecad.org/Std_ViewTrimetric).
I have a hard time figuring out how I can
* Determine the angles that those views use
* Do the same as FreeCAD in KiCAD and Blender

In case this is something you'd be interested in and willing to help with, please let me know so that we can chat elsewhere.

**Comment by blackbit42** [comment]
This is strange.
I left the Blender window alone after kicking off the import, 2 hours ago or so.
Now it is responsive again, the import did _not_ happen and there are no messages on the shell whatsoever.

**Comment by 30350n** [comment]
> Oh, I wasn't aware you're into FreeCAD too. This is super off-topic, I'll ask anyways (perhaps we should move this conversation somewhere else if it picks up pace...). What I would like to achieve is to get various renders of a KiCAD PCB from KiCAD itself, FreeCAD and Blender, all with the same 'view'. In FreeCAD there are some presets like [Std_ViewIsometric](https://wiki.freecad.org/Std_ViewIsometric) and [Std_ViewTrimetric](https://wiki.freecad.org/Std_ViewTrimetric). I have a hard time figuring out how I can
> 
>     * Determine the angles that those views use
> 
>     * Do the same as FreeCAD in KiCAD and Blender
> 
> 
> In case this is something you'd be interested in and willing to help with, please let me know so that we can chat elsewhere.

Hmm I also don't know a whole about this, but this sounds like it should be achievable using some basic linear algebra.

In Blender you can just directly set the cameras location, rotation, FOV, etc.:
![image](https://github.com/user-attachments/assets/bf3d14d3-f8c0-430d-9869-8e6b15796942)
![image](https://github.com/user-attachments/assets/6ac5522f-80cb-4b75-bb31-b7e1fbb680a0)

For KiCAD, it seems like you can setup "Viewports" in the 3D Viewer to Save different camera positions/rotations. These get then saved in the `.kicad_pro` file (for some reason) as a 4x4 Matrix (note the messed up order though). So you could probably just insert your wanted transformation in there. From what I can tell it's not possible to set focal length/FOV though, so you'd have to find out which FOV KiCAD's camera uses and match it in Blender/FreeCAD.
![image](https://github.com/user-attachments/assets/327dc49b-fcf4-4dc2-a8df-5c7c036a6dd6)

For FreeCAD it should definitely be possible via Python and I've just given it a quick google search and also seen some Macros floating around. It should definitely be possible, but I would also have to do more research here.

(Of course all the coordinate systems, scales/units, etc. most likely won't match, so you'll have to find suitable conversions between the softwares.)

**Comment by blackbit42** [comment]
Good suggestion, I'll do so, thank you.

**Comment by blackbit42** [comment]
> > the import did not happen
> 
> Are you sure about that? The imported PCBs will appear relatively small (as they are scaled _correctly_ in regards to Blender's units).

You were right.
1. PCB was very small
2. the default cube blocked the view

Reality is that I have practically no clue of Blender and still have to find my feet.

**Comment by blackbit42** [comment]
Progress...
I installed the free2ki mod into FreeCAD. That was easy.
The material modification and export too. I did that for one of the two large thingies in my KiCAD project for now.
Import into Blender is **fast**, rendering is **fast** too.
![image](https://github.com/user-attachments/assets/90301758-4952-424a-97c4-3299ea3aaef3)
I've noticed though that I've lost the multi-coloring of the relay.
I guess I have to take this into account when doing the material thing in FreeCAD?

Anyways, I must pull what I export from FreeCAD into KiCAD instead of what is there now, save that and export the entire board again, which shall then go into Blender, yes?

**Comment by blackbit42** [comment]
![image](https://github.com/user-attachments/assets/b14a36b9-a67b-4234-b678-7be42ff7e2e7)
I just gave it a try. In principle the process works, I think.
* KiCAD is happy to accept the newly exported 3D models from FreeCAD
* I can export from KiCAD and import into Blender (the latter being reasonably fast in comparison to before)
The color issue persists, though - again - I think I know the reason for that.
What puzzles me though currently is the incorrect size of the relay and the transformer.

**Comment by 30350n** [comment]
> I've noticed though that I've lost the multi-coloring of the relay.
> I guess I have to take this into account when doing the material thing in FreeCAD?

Hmm that should be something wrong on your side then, just tested it and it's working fine for me. I setup the materials like this (as an example):
![image](https://github.com/user-attachments/assets/573909c1-fbad-418d-a62b-075877a2ab8c)

and they appear correctly in Blender:
![image](https://github.com/user-attachments/assets/0746c824-e672-4bc6-a813-8bd9394abdbe)

> What puzzles me though currently is the incorrect size of the relay and the transformer.

`free2ki` (in contrast to other solutions, aka Step Up/default FreeCAD exports) actually scales the models **correctly** for KiCAD and Blender. My guess is that you directly replaced your old models (which had scaling applied) and didn't reset the scaling to 1.

Also, sidenote, you should probably not export that footprint/board mockup with the relay (to do so, select only the relay Part before hitting the free2ki export button).

**Comment by blackbit42** [comment]
![image](https://github.com/user-attachments/assets/d1ef2d8f-1bc2-4d41-afca-40182247a425)

I tried the same material color settings as you have them.
I must be doing something stupid...

> and didn't reset the scaling to 1

Where do I do that? FreeCAD? KiCAD?
What I have found is this, but it is (and was) set to 1.

![image](https://github.com/user-attachments/assets/53d8b2ee-4329-48c0-9d0f-2b8b559075bc)

**Comment by 30350n** [comment]
> I tried the same material color settings as you have them.

Hmm that's odd. And looking at your screenshot, the colors **do** seem to appear in KiCAD, right?
Any errors when importing the model in Blender? Oh actually: Are you sure you are using the modified VRML importer from `pcb2blender`? `Import -> X3D/VRML (.x3d/.wrl) (for pcb3d)`

KiCAD scaling looks correct. Is the scaling in FreeCAD correct too? How big is the relay in reality?

**Comment by blackbit42** [comment]
![image](https://github.com/user-attachments/assets/be4e07d7-345c-4468-bbad-a9059666b977)

Yes, in KiCAD I see color.
Yes, I am using the correct import dialog in Blender.
There are no messages on the shell where I've started Blender at all.
![image](https://github.com/user-attachments/assets/13002ecc-49ba-44ef-b813-c8ae98662ed2)
These are the dimensions from the official datasheet.
35.24 * 9.9 * 9.9 mm

**Comment by 30350n** [comment]
Very odd. Can you share the file? Also, just to make 100%, these .wrl files are exported using `free2ki`? Because by default `free2ki` actually exports compressed `.wrz` files. Maybe that's the issue actually?

**Comment by blackbit42** [comment]
![image](https://github.com/user-attachments/assets/8d8bb482-b1ae-443b-97ea-de01add8322a)

That was indeed the issue. I had used the export function of FreeCAD itself, not of `free2ki`.
Now, everything fell into place. Wonderful!

![image](https://github.com/user-attachments/assets/2f9da32b-8fdd-4894-8702-09fafbfadea0)

This is only a 'Workbench' render. The other 2 engines would take 8 hours or so. I am on a laptop with intel graphics...

I think that's it.
Thanks so much for your patient help with this, much appreciated.
Would you be interested to tinker with the viewports thing between the three programs?
Perhaps on an IRC or Discord channel where you are?

**Comment by 30350n** [comment]
Okay perfect, that explains it.

> Would you be interested to tinker with the viewports thing between the three programs?
> Perhaps on an IRC or Discord channel where you are?

I probably won't be able to spend much time on looking into this myself, but if you want to update me about your progress/findings or any issues you are running into, I'd be happy do communicate via discord DMs (my userid is `30350n`) ^^
