### ISSUE TITLE
Identical footprint references

### ISSUE THREAD

**Issue by Haschtl** [30350n/pcb2blender#9]
There is an Issue with multiple footprints with the same reference, which is possible in KiCAD....
It results in multiple identical filenames inside the zip-file:
![image](https://user-images.githubusercontent.com/11295204/208244772-1d202278-08c9-4884-ba20-202834f1da08.png)

In the import step, the duplicates are beeing ignored.
My suggestion would be to add the footprint-idx to the filename, e.g. like `name = f"{value}_{reference}_{j}.{i}"` with `j, footprint in enumerate(board.Footprints())` in `export.py`:
![image](https://user-images.githubusercontent.com/11295204/208245414-d9bfd1c7-23ab-4d76-bbbe-747f6968bd4d.png)

Another problem is, that I have 2 footprints for one model, which is not an ideal design strategy - but it is as it is... The footprints 30,31 and 34, 35 share the same model. This causes missing pads, because `has_model` is false for 30 and 34. 
I think there is not a real solution for it, except to add a configuration to disable the `has_model` filter

**Comment by 30350n** [comment]
Fixed! Thanks a lot, didn't think of that ^^
